---
# This playbook serves as scaffolding for creating users
- name: create group
  group: name=developers state=present
  sudo: yes
  tags: users

- name: create users
  user: shell=/bin/bash
        name="{{ item }}"
        groups=developers
        append=yes
  sudo: yes
  tags: users
  with_items: users

- name: add authorized keys
  authorized_key: user="{{ item }}" key="{{ lookup('file', '../public_keys/' + item + '.pub') }}"
  sudo: yes
  tags: users
  with_items: users

- name: correct permissions on .ssh
  file: "path=/home/{{ item }}/.ssh mode=0700 owner={{ item }} group={{ item }}"
  sudo: yes
  tags: users
  with_items: users
