language: python
python:
    - "2.7"
    - "3.4"

sudo: false

compiler:
    - gcc
before_install:
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then export PY3="true"; else export PY2="true"; fi
    - if [ -n "${PY3}" ]; then export IGNORE_PLUGINS=hdfs_assetstore,metadata_extractor; fi
    - cd "${HOME}"
    - npm install -g npm
    - git clone git://github.com/girder/girder
    - curl "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.2.tgz" | gunzip -c | tar x
    - cd mongodb-*/bin && export PATH="${PWD}:${PATH}"
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - cd "${HOME}"
    - curl -L "http://cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz" | gunzip -c | tar x
    - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
    - cd "${HOME}/girder/plugins"
    - ln -s "${TRAVIS_BUILD_DIR}" covalic
install:
    - cd "${HOME}/girder"
    - scripts/InstallPythonRequirements.py --mode=dev --ignore-plugins=${IGNORE_PLUGINS}
    - npm install
script:
    - mkdir _build
    - cd _build
    - cmake -DPYTHON_COVERAGE:BOOL=ON -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} "${HOME}/girder"
    - ctest -V -R covalic
