name: COVALIC Challenges
description: An application for hosting grand challenges.
version: 0.1.0
dependencies:
    - challenge
    - gravatar
    - romanesco
    - thumbnails
grunt:
    file: Gruntfile.js
    defaultTargets:
        - covalic-web
