name: COVALIC Challenges
description: An application for hosting grand challenges.
version: 0.1.0
dependencies:
    - gravatar
    - worker
    - thumbnails
grunt:
    file: Gruntfile.js
    defaultTargets:
        - covalic-web
