---
- name: Update apt cache
  apt: update_cache=yes
  sudo: yes
  tags: celery

# Install celery and necessary dependencies
- name: Install worker dependencies
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - rabbitmq-server
    - libffi-dev
    - libssl-dev
    - python-pip
    - python-dev
    - git
    - docker.io
  tags: celery

- name: Enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes
  sudo: yes
  tags: celery

- name: Pull latest covalic metrics Docker image
  sudo: yes
  command: docker pull girder/covalic-metrics:{{ covalic_metrics_version }}
  tags:
    - celery
    - deploy-update

- name: Clone romanesco worker
  sudo: yes
  git:
      repo: git://github.com/kitware/romanesco.git
      dest: /opt/romanesco
      accept_hostkey: yes
      force: yes
      version: "{{ romanesco_version }}"
  tags:
    - celery
    - deploy-update

- name: Remove R dependency from romanesco
  lineinfile:
      dest: /opt/romanesco/requirements.txt
      state: present
      regexp: '^rpy2'
      line: '# rpy2'
  sudo: yes
  tags:
    - celery
    - deploy-update

- name: Install worker pip dependencies
  pip: requirements=/opt/romanesco/requirements.txt
  sudo: yes
  tags:
    - celery
    - deploy-update

- name: Create local romanesco config file if it does not exist
  sudo: yes
  command: cp /opt/romanesco/romanesco/worker.dist.cfg /opt/romanesco/romanesco/worker.local.cfg creates=/opt/romanesco/romanesco/worker.local.cfg
  tags:
    - celery
    - deploy-update

- name: Set romanesco broker URL in config file
  lineinfile:
    dest: /opt/romanesco/romanesco/worker.local.cfg
    state: present
    regexp: '^broker='
    line: "broker=amqp://guest@localhost//"
  sudo: yes
  tags:
    - celery
    - deploy-update

- name: Change ownership of romanesco to correct user
  sudo: yes
  file: dest=/opt/romanesco mode=755 owner={{romanesco_exec_user}} group={{romanesco_exec_group}} state=directory recurse=yes
  tags:
    - celery
    - deploy-update

- name: Create Docker group
  group: name=docker state=present
  tags: celery

- name: Add romanesco user to Docker group
  user: shell=/bin/bash
        name={{romanesco_exec_user}}
        groups=docker
        append=yes
  sudo: yes
  tags: celery

- name: Restart docker daemon
  service: name=docker.io state=restarted enabled=yes
  sudo: yes
  tags:
    - celery
    - deploy-update

- name: Install celery worker as a service
  copy: src=celery_worker.conf dest=/etc/init/celery_worker.conf mode=644 owner=root
  sudo: yes
  tags: celery

- name: Restart celery worker as a service
  service: name=celery_worker state=restarted enabled=yes
  sudo: yes
  tags:
    - celery
    - deploy-update
