---
- name: MongoDB | Fetch GPG key
  sudo: yes
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  tags: mongodb

- name: MongoDB | Add 10 gen repository
  sudo: yes
  shell:
    echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list creates=/etc/apt/sources.list.d/10gen.list
  tags: mongodb

- name: MongoDB | Install latest mongodb
  sudo: yes
  apt: pkg={{ item }} update-cache=yes
  with_items:
    - mongodb-org-server
    - mongodb-org-tools
    - python-pip
  tags: mongodb

- name: Get the most recent version of pip
  pip: name=pip extra_args="-U"
  sudo: yes
  tags:
    - mongodb
    - deploy-update

- name: Get boto pip package
  pip: name=boto version=2.39.0
  sudo: yes
  tags:
    - mongodb
    - deploy-update

# TODO this will have to be redone for clustered mongo
# change the mongodb from listening only on the local ip to the internal ip
- name: Make mongo listen on private IP interface
  sudo: yes
  lineinfile:
    dest: /etc/mongod.conf
    state: present
    regexp: 'bind_ip = (.*)'
    line: "bind_ip = {{mongo_private_ip}}"
  tags:
    - mongodb
    - rewire

- name: Make mongo use the larger EBS volume for the database
  sudo: yes
  lineinfile:
    dest: /etc/mongod.conf
    state: present
    regexp: 'dbpath=(.*)'
    line: "dbpath={{ mongo_dbpath }}"
  tags:
    - mongodb

- name: Run mongo daemon
  sudo: yes
  service: name=mongod state=restarted
  tags:
    - mongodb
    - rewire

- name: Install backup_db.sh script
  sudo: yes
  template:
    dest: /home/ubuntu/backup_db.sh
    src: backup_db.sh
    mode: 0755
  tags:
    - mongodb
    - deploy-update

- name: Install S3 upload script
  sudo: yes
  template:
    dest: /home/ubuntu/upload_to_s3.py
    src: upload_to_s3.py
  tags:
    - mongodb
    - deploy-update
