---
- name: Create local inventory and vars file from AWS Covalic pod, requires environment variable pod to be defined
  hosts: tag_pod_{{pod}}
  connection: local
  gather_facts: false
  vars:
    - region: us-east-1
    - pub_key_name: covalic_admin
    - pod_set: "{{ groups.get('tag_pod_' + pod, []) }}"
    - celery_set: "{{ groups.get('tag_type_celery', []) | intersect(pod_set) }}"
    - girder_set: "{{ groups.get('tag_type_girder', []) | intersect(pod_set) }}"
    - mongo_set: "{{ groups.get('tag_type_mongodb', []) | intersect(pod_set) }}"
    - mq_set: "{{ groups.get('tag_type_mq', []) | intersect(pod_set) }}"

  tasks:
    - local_action: template src=templates/pod_inventory dest=pod_inventory/{{pod}}_pod
    - local_action: template src=templates/pod_vars dest=pod_dynamic_vars/{{pod}}_vars.yml
