---
- name: Create local inventory and vars file from AWS Covalic pod, requires environment variable pod to be defined
  hosts: tag_pod_{{pod}}
  connection: local
  gather_facts: false
  vars:
    - region: us-east-1
    - pub_key_name: "covalic_admin"

  tasks:
    - local_action: template src=templates/pod_inventory dest=pod_inventory/{{pod}}_pod
    - local_action: template src=templates/pod_vars dest=pod_dynamic_vars/{{pod}}_vars.yml
