---
- name: Stop instances with with a tag of pod for a specific pod value
  hosts: "tag_pod_{{pod}}"
  connection: local
  gather_facts: false
  vars:
    - region: us-east-1

  tasks:

    - name: Stop instances for pod '{{pod}}'
      local_action:
        module: ec2
        state: stopped
        region: "{{ region }}"
        instance_ids: "{{hostvars[item]['ec2_id']}}"
      with_items: "groups.tag_pod_{{pod}}"
